apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: mongodb-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mongodb
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb
  endpoints:
    - port: 9216
      interval: 30s